using HRApiLibrary.Models._00_MainPis;
using HRApiLibrary.Models._10_Pis;

namespace HRApiLibrary.DataAccess._10_Pis.Interface
{
    public interface I_10_EmpmasDataAccess
    {
        Task<EmpmasModel?> _01Empmas(EmpmasModel empmas, string? schema, string? conn);
        Task<EmpmasAddressModel?> _01EmpmasAddress(int? id, EmpmasAddressModel empmasaddress, string? schema, string? conn);
        Task<EmpmasAddressModel?> _01EmpmasAddress_EmailOnly(int? id, string? emailAdd, string? schema, string? conn);
        Task<EmpmasCharRefModel?> _01EmpmasCharRef(EmpmasCharRefModel empmascharref, string? schema, string? conn);
        Task<EmpmasClearancePhModel?> _01EmpmasClearancePh(int? id, EmpmasClearancePhModel empmasclearanceph, string? schema, string? conn);
        Task<EmpmasEducateModel?> _01EmpmasEducate(EmpmasEducateModel empmaseducate, string? schema, string? conn);
        Task<EmpmasEducateRefModel?> _01EmpmasEducateRef(int? id, EmpmasEducateRefModel empmaseducateref, string? schema, string? conn);
        Task<EmpmasEmploymentModel?> _01EmpmasEmployment(EmpmasEmploymentModel empmasemployment, string? schema, string? conn);
        Task<EmpmasFamilyModel?> _01EmpmasFamily(EmpmasFamilyModel empmasfamily, string? schema, string? conn);
        Task<EmpmasFamilyRefModel?> _01EmpmasFamilyRef(string? code, string? name, string? schema, string? conn);
        Task<List<EmpmasEmergencyContactModel?>?> _02EmpmasEmergencyContactList(int? empmasId, string? schema, string? conn);
        Task<EmpmasGovPhModel?> _01EmpmasGovPh(int? id, EmpmasGovPhModel empmasgovph, string? schema, string? conn);
        Task<EmpmasInsuranceModel?> _01EmpmasInsurance(EmpmasInsuranceModel empmasinsurance, string? schema, string? conn);
        Task<EmpmasPIModel?> _01EmpmasPI(int? id, EmpmasPIModel empmaspi, string? schema, string? conn);
        Task<EmpmasRelativesModel?> _01EmpmasRelatives(EmpmasRelativesModel empmasrelatives, string? schema, string? conn);
        Task<EmpmasRelativesRefModel?> _01EmpmasRelativesRef(string? code, string? name, string? schema, string? conn);
        Task<EmpmasSecLicModel?> _01EmpmasSecLic(int? id, EmpmasSecLicModel empmasseclic, string? schema, string? conn);
        Task<EmpmasTrainingModel?> _01EmpmasTraining(EmpmasTrainingModel empmastraining, string? schema, string? conn);
        Task<EmpmasModel?> _02Empmas(int? id, string? schema, string? conn);
        Task<EmpmasModel?> _02BySystemId(int? systemId, string? pisdb, string? conn);
        Task<List<EmpmasInternalModel?>?> _02BySystemIdList(int? systemId, string? pisdb, string? conn);
        Task<EmpmasAddressModel?> _02EmpmasAddress(int? id, string? schema, string? conn);
        Task<EmpmasCharRefModel?> _02EmpmasCharRef(int? id, string? schema, string? conn);
        Task<List<EmpmasCharRefModel?>> _02EmpmasCharRefList(int? empmasId, string? schema, string? conn);
        Task<EmpmasClearancePhModel?> _02EmpmasClearancePh(int? id, string? schema, string? conn);
        Task<EmpmasEducateModel?> _02EmpmasEducate(int? id, string? schema, string? conn);
        Task<List<EmpmasEducateModel?>> _02EmpmasEducateList(int? empmasId, string? schema, string? conn);
        Task<EmpmasEducateRefModel?> _02EmpmasEducateRef(int? id, string? schema, string? conn);
        Task<List<EmpmasEducateRefModel?>?> _02EmpmasEducateRef(string? schema, string? conn);
        Task<EmpmasEmploymentModel?> _02EmpmasEmployment(int? id, string? schema, string? conn);
        Task<List<EmpmasEmploymentModel?>> _02EmpmasEmploymentList(int? empmasId, string? schema, string? conn);
        Task<EmpmasFamilyModel?> _02EmpmasFamily(int? id, string? schema, string? conn);
        Task<List<EmpmasFamilyModel?>> _02EmpmasFamilyList(int? empmasId, string? schema, string? conn);
        Task<EmpmasFamilyRefModel?> _02EmpmasFamilyRef(string? code, string? schema, string? conn);
        Task<List<EmpmasFamilyRefModel?>?> _02EmpmasFamilyRefList(string? schema, string? conn);
        Task<EmpmasGovPhModel?> _02EmpmasGovPh(int? id, string? schema, string? conn);
        Task<EmpmasInsuranceModel?> _02EmpmasInsurance(int? id, string? schema, string? conn);
        Task<EmpmasPIModel?> _02EmpmasPI(int? id, string? schema, string? conn);
        Task<EmpmasRelativesModel?> _02EmpmasRelatives(int? id, string? schema, string? conn);
        Task<List<EmpmasRelativesModel?>> _02EmpmasRelativesList(int? empmasId, string? schema, string? conn);
        Task<EmpmasRelativesRefModel?> _02EmpmasRelativesRef(string? code, string? schema, string? conn);
        Task<List<EmpmasRelativesRefModel?>?> _02EmpmasRelativesRefList(string? schema, string? conn);
        Task<EmpmasSecLicModel?> _02EmpmasSecLic(int? id, string? schema, string? conn);
        Task<List<EmpmasSecLicModel?>?> _02EmpmasSecLicList(int? id, string? schema, string? conn);
        Task<EmpmasTrainingModel?> _02EmpmasTraining(int? id, string? schema, string? conn);
        Task<List<EmpmasTrainingModel?>> _02EmpmasTrainingList(int? empmasId, string? schema, string? conn);
        Task<List<EmpmasGovPhModel?>?> _02EmpmasGovPhList(int? id, string? schema, string? conn);
        Task<List<EmpmasInsuranceModel?>?> _02EmpmasInsuranceList(int? id, string? schema, string? conn);
        Task<List<EmpmasInsuranceModel?>?> _02EmpmasInsuranceListByEmpmasId(int? empmasid, string? schema, string? conn);
        Task<List<EmpmasClearancePhModel?>?> _02EmpmasClearancePhList(int? id, string? schema, string? conn);
        Task<EmpmasFamilyRefModel?> _03EmpmasFamilyRef(string? code, string? name, string? schema, string? conn);
        Task<EmpmasModel?> _03Empmas(int? id, EmpmasModel empmas, string? schema, string? conn);
        Task<EmpmasModel?> _03EmpmasWithSystemId(int? id, EmpmasModel empmas, string? schema, string? conn);
        Task<EmpmasAddressModel?> _03EmpmasAddress(int? id, EmpmasAddressModel empmasaddress, string? schema, string? conn);
        Task<EmpmasCharRefModel?> _03EmpmasCharRef(int? id, EmpmasCharRefModel empmascharref, string? schema, string? conn);
        Task<EmpmasClearancePhModel?> _03EmpmasClearancePh(int? id, EmpmasClearancePhModel empmasclearanceph, string? schema, string? conn);
        Task<EmpmasEducateModel?> _03EmpmasEducate(int? id, EmpmasEducateModel empmaseducate, string? schema, string? conn);
        Task<EmpmasEducateRefModel?> _03EmpmasEducateRef(int? id, EmpmasEducateRefModel empmaseducateref, string? schema, string? conn);
        Task<EmpmasEmploymentModel?> _03EmpmasEmployment(int? id, EmpmasEmploymentModel empmasemployment, string? schema, string? conn);
        Task<EmpmasFamilyModel?> _03EmpmasFamily(int? id, EmpmasFamilyModel empmasfamily, string? schema, string? conn);
        Task<EmpmasGovPhModel?> _03EmpmasGovPh(int? id, EmpmasGovPhModel empmasgovph, string? schema, string? conn);
        Task<EmpmasInsuranceModel?> _03EmpmasInsurance(int? id, EmpmasInsuranceModel empmasinsurance, string? schema, string? conn);
        Task<EmpmasPIModel?> _03EmpmasPI(int? id, EmpmasPIModel empmaspi, string? schema, string? conn);
        Task<EmpmasRelativesModel?> _03EmpmasRelatives(int? id, EmpmasRelativesModel empmasrelatives, string? schema, string? conn);
        Task<EmpmasRelativesRefModel?> _03EmpmasRelativesRef(string? code, string? name, string? schema, string? conn);
        Task<EmpmasSecLicModel?> _03EmpmasSecLic(int? id, EmpmasSecLicModel empmasseclic, string? schema, string? conn);
        Task<EmpmasTrainingModel?> _03EmpmasTraining(int? id, EmpmasTrainingModel empmastraining, string? schema, string? conn);
        Task<EmpmasFamilyRefModel?> _04EmpmasFamilyRef(string? code, string? schema, string? conn);
        Task<EmpmasModel?> _04Empmas(int? id, string? schema, string? conn);
        Task<EmpmasAddressModel?> _04EmpmasAddress(int? id, string? schema, string? conn);
        Task<EmpmasCharRefModel?> _04EmpmasCharRef(int? id, string? schema, string? conn);
        Task<EmpmasClearancePhModel?> _04EmpmasClearancePh(int? id, string? schema, string? conn);
        Task<EmpmasEducateModel?> _04EmpmasEducate(int? id, string? schema, string? conn);
        Task<EmpmasEducateRefModel?> _04EmpmasEducateRef(int? id, string? schema, string? conn);
        Task<EmpmasEmploymentModel?> _04EmpmasEmployment(int? id, string? schema, string? conn);
        Task<EmpmasFamilyModel?> _04EmpmasFamily(int? id, string? schema, string? conn);
        Task<EmpmasGovPhModel?> _04EmpmasGovPh(int? id, string? schema, string? conn);
        Task<EmpmasInsuranceModel?> _04EmpmasInsurance(int? id, string? schema, string? conn);
        Task<EmpmasPIModel?> _04EmpmasPI(int? id, string? schema, string? conn);
        Task<EmpmasRelativesModel?> _04EmpmasRelatives(int? id, string? schema, string? conn);
        Task<EmpmasRelativesRefModel?> _04EmpmasRelativesRef(string? code, string? schema, string? conn);
        Task<EmpmasSecLicModel?> _04EmpmasSecLic(int? id, string? schema, string? conn);
        Task<EmpmasTrainingModel?> _04EmpmasTraining(int? id, string? schema, string? conn);
        Task<EmpmasInternalModel?> _01EmpmasInternal(EmpmasInternalModel empmas, string? schema, string? conn);
        Task<EmpmasInternalModel?> _02EmpmasInternal(int? id, string? schema, string? conn);
        Task<EmpmasInternalModel?> _03EmpmasInternal(int? id, EmpmasInternalModel empmas, string? schema, string? conn);
        Task<EmpmasInternalModel?> _04EmpmasInternal(int? id, string? schema, string? conn);
        Task<EmpmasModel?> _02ByUserId(int? id, string? schema = "MainPis", string? conn = "MySqlConn");
        Task<List<EmpmasModel?>?> _02By1stLetterRange(string? firstLetter, string? secondLetter, string? schema = "MainPis", string? conn = "MySqlConn");
        Task<List<EmpmasModel?>?> _02SearchName(string? skey, string? schema = "MainPis", string? conn = "MySqlConn");
        Task<EmpmasModel?> _01EmpmasV1(EmpmasModel empmas, string? schema, string? conn);
        Task<EmpmasModel?> _01EmpmasWithSystemId(EmpmasModel empmas, string? schema, string? conn);
        Task<EmpmasAddressModel?> _02EmpmasAddress_ByIdAndEmail(int? id, string? email, string? schema, string? conn);
        Task<List<EmpmasAddressModel?>?> _02EmpmasAddress_ByEmailNotTheOwner(int? id, string? email, string? schema, string? conn);
        Task<List<EmpmasModel?>?> _02Empmas_EmpnumberOwnedByOthers(int? id, string? empnumber, string? schema, string? conn);
        Task<DeprecModel?> _01Deprec(DeprecModel deprec, string? schema, string? conn);
        Task<DeprecModel?> _02Deprec(int? id, string? schema, string? conn);
        Task<DeprecModel?> _03Deprec(DeprecModel deprec, string? schema, string? conn);
        Task<DeprecModel?> _04Deprec(int? id, string? schema, string? conn);
        Task<List<EmpmasPIModel?>?> _02EmpmasPIs(int? id, string? schema, string? conn);
        Task<List<DeprecModel?>?> _02Deprecs(int? id, string? schema, string? conn);
        Task<List<EmpmasAddressModel?>?> _02EmpmasAddresss(int? id, string? schema, string? conn);
    }
}